### ISSUE TITLE
Shopping cart system for ordering tickets

### ISSUE THREAD

**Issue by maartenhbe** [ZeusWPI/Gandalf#452]
The flow I have in mind:

1. People click a button "Buy"
2. People get a list of all available tickets with an inputbox next to it if it's not a member only ticket. Via this inputbox they can buy e.g. 10 tickets of a certain type.
3. People enter the names and e-mailadresses. A member only ticket is fixed on their name.
4. They receive a payment mail to pay all the tickets at once.
5. After the payment is processed, each user receives his/her ticket on the e-mailadres entered in step 3.

We will need an "Orders" tab which display all payment info (code, amount paid, etc.). The "Registrations" tab will still contain a list of all tickets but without payment info.

Important here is the decoupling of the concepts Ticket and Order. An Order can have multiple tickets in this new flow.

What do you think? Big rework but this would allow people to buy tickets for them and their friends in one effort.

**Comment by Silox** [comment]
Closing in favour of #460
