### ISSUE TITLE
Remove the bank-payment notice when a free ticket is selected

### ISSUE THREAD

**Issue by TomNaessens** [ZeusWPI/Gandalf#480]

**Comment by BrentyMcFatty** [comment]
fbb0cd10a6dce3fc77752b86dbba93ed2b865bfd :
Dit is de eerste volle functionele commit,
waarbij je de bug hebt dat als je een € in de naam van je event zet, de payment notice nog altijd verschijnt, ook al is de event gratis (is 'event' nu onzijdig of niet?)

286766adf62fe28ed1aaea892f756be5dd71b5df :
Dit is de commit waarbij ik probeerde de bug eruit te krijgen, en ik vrij zeker ben dat ik op het juiste spoor zit. Maar ik ken de precieze syntax van ruby niet, dus ik ben er niet geraakt na veel proberen. Hierbij zou graag wat hulp krijgen.

**Comment by TomNaessens** [comment]
Create https://github.com/ZeusWPI/Gandalf/pull/658 for easier review comments
