### ISSUE TITLE
Hide old events

### ISSUE THREAD

**Issue by Thoge** [ZeusWPI/Gandalf#489]
Old events clutter the overview in Gandalf. Events that are over should be hidden from the users.

For admins it would be nice to have a checkbox to view old events. Old events can be useful to review the next year.

**Comment by maartenhbe** [comment]
Just create a accordian with subsections only for admins called "Previous events" and "Current events" which one can collapse.

Example: http://www.kinevanheule.be/#specialisaties

**Comment by maartenhbe** [comment]
This one can be closed I think?
