### ISSUE TITLE
Formatting of mail is gone

### ISSUE THREAD

**Issue by maartenhbe** [ZeusWPI/Gandalf#494]
When mailing registered people, formatting is lost.

**Comment by Silox** [comment]
Is it just not there, or was it there at some point in the past?


On 18 Mar 2015 at 16:09:05, Maarten (notifications@github.com) wrote:

When mailing registered people, formatting is lost.

**Comment by maartenhbe** [comment]
I thought it was there but it disappeared.

Formatting (newlines and stuff where there in the past.

**Comment by TomNaessens** [comment]
Nope, still there.
