### ISSUE TITLE
Search by name for scanning

### ISSUE THREAD

**Issue by Thoge** [ZeusWPI/Gandalf#496]
Have a search by name field on the scan page. This is especially usefull for persons who failed to have the barcode printed on their ticket or who did not bring it.

I believe there is no possible way to "scan" a person without valid barcode in the current setup.

**Comment by Silox** [comment]
Note to self (and @Iasoon): Typeahead creates an object in the Local Storage which stores the datums and also the search trie. So when modifying the attributes which can be searched for, the local storage should be cleared.
