### ISSUE TITLE
Mails are not always sent

### ISSUE THREAD

**Issue by Thoge** [ZeusWPI/Gandalf#531]
We have received complains about people buying tickets, but not receiving confirmation mails.

**Comment by Silox** [comment]
Are these mostly/all hotmail or MS adresses? It seems that the UGent is getting blocked my the Microsoft mailservers more and more. Nothing we can do.

**Comment by Thoge** [comment]
First known issue was for La Fiesta de la Proclamación on 30 June 2015

**Comment by sophiastr** [comment]
i want to deal with this issue.
I am interested in contributing to the project you are developing.
Do you still need help?

**Comment by sophiastr** [comment]
Thank you for the answer.
I want to contribute code and work intensively, so I will work on several issues. Because I do not belong to Ghent University, can I get an account to access the extra features?

**Comment by redfast00** [comment]
You don't need an account, you can just develop locally, I think the README has instructions on how to setup Gandalf.

**Comment by TomNaessens** [comment]
It's been a while but there's a login backdoor at `POST /dev_login`, accessible through a button: https://github.com/ZeusWPI/Gandalf/blob/cac72706bc151516c854143858655e1d3bd76cd6/app/views/layouts/_login.html.erb#L16
It goes to `users#login` https://github.com/ZeusWPI/Gandalf/blob/master/config/routes.rb#L82 which logs you into an admin account: https://github.com/ZeusWPI/Gandalf/blob/master/app/controllers/users_controller.rb

**Comment by TomNaessens** [comment]
They're background jobs now, let's see if it still happens.
