### ISSUE TITLE
Creating partners: Email adress with uppercase characters is rejected

### ISSUE THREAD

**Issue by benoitdevrieze** [ZeusWPI/Gandalf#533]
Example: Create a partner with email Daniel.Termont@gent.be
This results in the error: "Email is invalid"

**Comment by Silox** [comment]
Fix: add `A-Z` to https://github.com/ZeusWPI/Gandalf/blob/master/app/validators/email_validator.rb#L3

**Comment by TomNaessens** [comment]
Tested locally, this just works.
