### ISSUE TITLE
Request more information from user

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/Gandalf#543]
- titles (Prof./Dr./Ms./Mr.) and I18N
- job title 

But it should be optional, and configurable on event basis.

**Comment by Silox** [comment]
Should add Mx. (https://en.wikipedia.org/wiki/Mx_(title)) too as a title option

**Comment by R13N** [comment]
Please add [Mx.](https://en.wikipedia.org/wiki/Mx_(title)) to the titles.
