### ISSUE TITLE
Check deletion of access level of a registration

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/Gandalf#555]
see https://github.com/ZeusWPI/Gandalf/commit/640f2f2927903c840d8a28bcffd15890669ab934#commitcomment-21466053

**Comment by Silox** [comment]
This should be impossible from the UI (check: https://github.com/ZeusWPI/Gandalf/blob/master/app/views/access_levels/_access_level.html.erb#L17) so or this does not work, or someone did a thing in the console
