### ISSUE TITLE
Be able to use emoji's in event emoji's and titles

### ISSUE THREAD

**Issue by TomNaessens** [ZeusWPI/Gandalf#574]
💣

**Comment by NuttyShrimp** [comment]
I guess this is regarding the collation in the DB no?

**Comment by redfast00** [comment]
Yes, it is. I think we might have fixed it, not sure

**Comment by NuttyShrimp** [comment]
It works in a dev env via rails. Could not get the docker env working for development

**Comment by TomNaessens** [comment]
It's not working on production. To reproduce:

- Sign into the app (backdoor: [users/auth/zeuswpi](https://event.student.ugent.be/users/auth/zeuswpi))
- Edit or create an existing event
- Use 💣 in the title

Not sure why, I think I checked the most common issues (collations) but couldn't find a reason why it isn't working. This should be reproducible in development as well

**Comment by TomNaessens** [comment]
> It works in a dev env via rails. Could not get the docker env working for development

The docker env is only for production, I'll see if I can create one to use for local development as well.

**Comment by NuttyShrimp** [comment]
Issue seems to be fixed with the latest commit

**Comment by TomNaessens** [comment]
Sadly not, still crashes on production so there must be something wrong/different with the database setup over there.
