### ISSUE TITLE
Use rich text editor when sending email

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/Gandalf#653]
My mail came out a bit uglier than intended.

![image](https://user-images.githubusercontent.com/10746993/202163394-be521d00-7477-41fe-94ed-085f69697288.png)

The "HTML body" field in the Gandalf send mail functionality was not that clear to me, this could be explained a bit more. Alternatively, we could add a what you see is what you get editor (as done with the event creation form)

**Comment by TomNaessens** [comment]
Well, we should just not strip newlines 😀
